name: Run Strava Data Fetcher

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade numpy pandas
          pip install -r requirements.txt

      - name: Decode Google Credentials
        shell: bash
        run: echo "${{ secrets.GCP_CREDENTIALS }}" | base64 --decode > service-account.json

      - name: Run Strava Fetcher Script
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          GOOGLE_SHEETS_NAME: ${{ secrets.GOOGLE_SHEETS_NAME }}
          STRAVA_CLUB_ID: ${{ secrets.STRAVA_CLUB_ID }}
        run: python fetch_data.py
